import "./globals.css";
import ClientLayout from "./components/ClientLayout";

export const metadata = {
  title: "NEKO SOFTWARE ENGINEERING CO.,LTD.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="th">
      <body>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
